import Head from "next/head";
import Image from "next/image";
import HeroSection from "../src/components/HeroSection";
import { animated } from "react-spring";

import Navbar from "../src/components/Navbar";
import About from "../src/components/About";
import Services from "../src/components/Services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Loop Forward</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <About />
      <Services />
    </div>
  );
}
