import Head from "next/head";
import Image from "next/image";
import HeroSection from "../src/components/HeroSection";

import Navbar from "../src/components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Loop Forward</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
    </div>
  );
}
